version: 2.1
workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          context:
            - GITHUB
            - NPM          
jobs:
  build_and_deploy:
    working_directory: ~/package
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Compile, Run Tests and Deploy Package
          command: |
            yarn
            yarn test
            yarn release
